cards = {
    {question="When should you use snapshots?", answer="When the appliance is first installed OR prior to performing an upgrade"},
    {question="Snapshots create a binary file image of which disk partition?", answer="root"},
    {question="What is NOT included in a snapshot?", answer="Log partition (no fw logs preserved)"},
    {question="Are snapshots appliance or version specific?", answer="Appliance, but not version."},
    {question="When to use backups (not snapshots)?", answer="Regularly for DR, and before performing a hardware upgrade"},
    {question="What is NOT included in a backup?", answer="OS, drivers, hot fixes"},
    {question="Are backups appliance or version specific?", answer="Not appliance specific, but version and hot fix must match"},
    {question="What are the 4 database domains inside of the SMS?", answer="Global, User, System, Log"},
    {question="What is stored in the Gaia OS database?", answer="IP config, Users, etc..."},
    {question="What port does SmartConsole use?", answer="TCP 19009"},
    {question="What is the main difference between a CPUSE and Advanced Upgrade?", answer="Advanced exports the entire management database."},
    {question="A CPUSE upgrade automatically performs a _______ before the upgrade.", answer="snapshot"},
    {question="When must an upgrade target have the same IP address configuration?", answer="When the environment uses only IPv4 or IPv6"},
    {question="When upgrading SMS from 77.x to 80.x, what is the preferred method with the Least Risk of Downtime?", answer="Advanced Upgrade with Database Migration"},
    {question="When migrating settings, should you use the older or newer version of the migrate tool located at $FWDIR/bin/upgrade_tools?", answer="Use the newer version"},
    {question="Which script exports the management database and CP Config during a R80.40 to R81.10 migration?", answer="/opt/CPsuite-R80.40/fw1/scripts"},
    {question="Is an HA Failover between SMSs automatic or manual?", answer="manual"},
    {question="What is required for 2 SMSs to sync?", answer="Same version AND hotfixes, Secondary server must be licensed, identical install and upgrade paths."},
    {question="What does the Collision status mean for an SMS in HA?", answer="The two SMSs have different policies and/or databases, one must be overwritten."},
    {question="What 3 things can trigger a sync between 2 SMSs in HA?", answer="When the 2nd server is first defined, when a manual sync is performed, when changes are published (delta sync)"},
    {question="When connecting SmartConsole to an SMS, what is required of that SMS for the connection to have Read/Write permissions?", answer="The SMS must be the Active one (not standby in HA)"},
    {question="What must you do to get a Gateway to sync with a Secondary SMS?", answer="Add the Secondary SMS to the ‘fetch policy’ list on the gateway object.  Likewise, if you want to get logs from a Secondary SMS, you can edit the ‘Log Distribution’ lists on the gateway object."},
    {question="Do Log Servers perform policy management?", answer="No, they are only repositories for Security Gateway Logs"}
}