cards = {
    {question="When should you use snapshots?", answer="When the appliance is first installed OR prior to performing an upgrade"},
    {question="Snapshots create a binary file image of which disk partition?", answer="root"},
    {question="What is NOT included in a snapshot?", answer="Log partition (no fw logs preserved)"},
    {question="Are snapshots appliance or version specific?", answer="Appliance, but not version."},
    {question="When to use backups (not snapshots)?", answer="Regularly for DR, and before performing a hardware upgrade"},
    {question="What is NOT included in a backup?", answer="OS, drivers, hot fixes"},
    {question="Are backups appliance or version specific?", answer="Not appliance specific, but version and hot fix must match"},
    {question="What are the 4 database domains inside of the SMS?", answer="Global, User, System, Log"},
    {question="What is stored in the Gaia OS database?", answer="IP config, Users, etc..."},
    {question="What port does SmartConsole use?", answer="TCP 19009"},
    {question="What is the main difference between a CPUSE and Advanced Upgrade?", answer="Advanced exports the entire management database."},
    {question="A CPUSE upgrade automatically performs a _______ before the upgrade.", answer="snapshot"},
    {question="When must an upgrade target have the same IP address configuration?", answer="When the environment uses only IPv4 or IPv6"},
    {question="When upgrading SMS from 77.x to 80.x, what is the preferred method with the Least Risk of Downtime?", answer="Advanced Upgrade with Database Migration"},
    {question="When migrating settings, should you use the older or newer version of the migrate tool located at $FWDIR/bin/upgrade_tools?", answer="Use the newer version"},
    {question="Which script exports the management database and CP Config during a R80.40 to R81.10 migration?", answer="/opt/CPsuite-R80.40/fw1/scripts"},
    {question="Is an HA Failover between SMSs automatic or manual?", answer="manual"},
    {question="What is required for 2 SMSs to sync?", answer="Same version AND hotfixes, Secondary server must be licensed, identical install and upgrade paths."},
    {question="What does the Collision status mean for an SMS in HA?", answer="The two SMSs have different policies and/or databases, one must be overwritten."},
    {question="What 3 things can trigger a sync between 2 SMSs in HA?", answer="When the 2nd server is first defined, when a manual sync is performed, when changes are published (delta sync)"},
    {question="When connecting SmartConsole to an SMS, what is required of that SMS for the connection to have Read/Write permissions?", answer="The SMS must be the Active one (not standby in HA)"},
    {question="What must you do to get a Gateway to sync with a Secondary SMS?", answer="Add the Secondary SMS to the 'fetch policy' list on the gateway object.  Likewise, if you want to get logs from a Secondary SMS, you can edit the 'Log Distribution' lists on the gateway object."},
    {question="Do Log Servers perform policy management?", answer="No, they are only repositories for Security Gateway Logs"},
    {question="Which ClusterXL Upgrade Method is good for when you can allow the most network downtime?", answer="Minimal Effort Upgrade."},
    {question="Which ClusterXL Upgrade Method is good for when you cannot allow network downtime but dropped packets are allowed (Connections initiated through the old-version cluster member are dropped when it is upgraded)?", answer="Zero Downtime Upgrade"},
    {question="Which ClusterXL Upgrade Method is good for when absolutely no downtime or drops can be allowed?", answer="Multi-Version Cluster Upgrade (MVCU)"},
    {question="What are the exceptions to MVCU’s no-drop stipulation?", answer="Remote VPN connections, Static NAT if using VMAC, Identity Awareness, DLP connections, Threat Emulations"},
    {question="What is a Gaia Fast Deployment mechanism that allows fast and easy deployment of gateways and SMSs, resulting in a Clean installed server with desired version and Hotfixes?", answer="Blink Utility (~5-7 minutes for Security Gateway, ~10-16 for SMS"},
    {question="What are the 5 upgrade steps?", answer="1. Plan process (order up upgrade, right versions, etc…)\n2. Backups, including custom config files, OFF of the appliance being upgraded\n3. Upgrade STANDBY members of the cluster\n4. Force failover to one of the standby members\n5. Upgrade remaining"},
    {question="For an MVCU upgrade, how to do you bring upgraded servers online?", answer="set cluster member mvc on"},
    {question="For an MVCU upgrade, how to do you bring the active server down?", answer="clusterXL_admin down (preferred)\nOR: set cluster admin down"},
    {question="What Security Gateway Upgrade option allows SmartConsole to deploy JumboHF and Upgrade packages and allows up to 10 gateways to be installed simultaneously?", answer="Central Deployment in SmartConsole"},
    {question="What are the 4 requirements for Central Deployment in SmartConsole?", answer="Write permissions on SmartUpdate\nCPUSE agent must be current\nGateway must have a policy installed\nCannot be done individually on clusters"},
    {question="What are some limitations of Central Deployment in SmartConsole?", answer="Cannot be used on Standalone environment, Non-gateways, Members of Full-HA Clusters, Global-use gateways, or gateways in load-sharing mode"},
    {question="What Cluster mode update Prepares the Access Control Policy for the Cluster and Changes the version in the Cluster object?", answer="High Availability Mode Clusters"},
    {question="Which command displays a listing of Check Point processes?", answer="cpwd_admin list"},
    {question="Which command displays all running processes?", answer="ps aux (you can pipe to grep for a specific process)"},
    {question="What is a good alternative to cpconfig when you need to use the functionality for scripting?", answer="cp_conf"},
    {question="How do you set the cli environment for users (debug level, prompt, output formatting, echo-cmd, etc…)?", answer="set clienv"},
    {question="What two commands change the timeout for the CLI and the GAIA web GUI?", answer="set inactivity-timeout\nset web session-timeout"},
    {question="How to you change the expert password in a script without having the new password in the script?", answer="set expert-password-hash <hash>"},
    {question="What command do you use to check for a specific listening port number?", answer="netstat -tulnp | grep <port>"},
    {question="What command do you use to check for a connection on a specific port?", answer="netstat -nạp | grep :<port>"},
    {question="Which of the 3 CheckPoint Security Processes deals with SmartConsole and SmartView Monitor/Event?", answer="GUI Clients"},
    {question="Which of the 3 Checkpoint Security Processes is responsible for ALL management operations for the databases, consoles, log files, and distribution of policy to GW?", answer="SMS"},
    {question="Which of the 3 Checkpoint Security Processes is responsible for enforcing the Security Policies configured on the SMS?", answer="Security Gateways"},
    {question="What are the functions of these Important Ports: TCP 19009, 9009, 18190, 257, 18120, 18264 and 18265", answer="19009 - remote communications with SmartConsole\n9009 - local SIC communications\n18190 - Connects to CPMI for legacy ops (SmartDashboard)\n257 - Delivers Logs form Gateway to SMS\n18120 - SMS pushes SIC certs\n18264 & 18265 - retrieve the CRL for the ICA Management Tool"},
    {question="Which SMS-Specific Check Point Management Process provides the architecture fore the security environment and allows the GUI clients to communicate with the SMS over 19009?", answer="Cpm (Check Point Management Process)"},
    {question="Which Check Point Management Process is the key process on all CheckPoint products, required by SIC, policy install, and application monitor (ports 18191 & 18211)?", answer="CPD (Check Point Daemon) "},
    {question="Which Check Point Management Process allows other processes to forward logs to external Log servers on port 257?", answer="FWD (Firewall Daemon)"},
    {question="Which Check Point Management Process is the “child” process of the FWD and manages the SMS for protocol enforcement?", answer="FWSSD"},
    {question="Which Check Point Management Process invokes and monitors key/critical processes?", answer="CPWD (Check Point Watchdog Daemon) (cpwd_admin command)"},
    {question="Which SMS-Specific Check Point Management Process provides GUI communication/authentication, database manipulation and policy compilation?", answer="FWM (Firewall Management)"},
    {question="Which SMS-Specific Check Point Management Process requires a specific script to investigate the process status, beyond running cpwd_admin list, and what is the path to that script?", answer="CPM (Check Point Management); $FWDIR/scripts/cpm_status.sh"},
    {question="Which SMS-Specific Check Point Management Process is responsible for HA of SMSs?", answer="FWMHA"},
    {question="Which SMS-Specific Check Point Management Processes are used for indexing and parsing logs?", answer="SOLR/INDEXER/SMARTLOG_SERVER/lpd"},
    {question="Which SMS-Specific Check Point Management Processes are used for SmartEvent?", answer="RFL/SMARTVIEW"},
    {question="What 4 processes are Gateway Specific?", answer="FWK_FORKER/FWK_WD\nSXL_STATD\nCIHS\nRAD"},
    {question="What features allow you to run scripts via SmartConsole, accessed through the Gateways & Servers view?", answer="One Time Script and Scripts Repository"},
    {question="What scripting feature allows scripts/tasks to be run on specific triggers?", answer="Smart Tasks"},
    {question="When does a packet enter the Inspection Module?", answer="After it is determined to continue an existing connection (New connections do NOT enter the module)"},
    {question="In Column-Based matching, in what order are the columns matched to the packet?", answer="First by Destination Host, Second by Source Host, and finally by Port."},
    {question="In Column-Based matching, if multiple rules are matched, which one is used?", answer="The highest priority rule"},
    {question="How is the Management plane separated from the Data Plane (MDPS) on the network level?", answer="Devices have a management interface with a separate routing domain."},
    {question="How is the Management plane separated from the Data Plane (MDPS) on the computing level?", answer="A kernel instance core is assigned to process mgmt traffic only."},
    {question="How does the Kernel Mode communicate with the upper User Mode?", answer="KM sets flags/traps, the changes of which are detected by the User Mode process."},
    {question="How does the User Mode communicate with the Kernel Mode?", answer="UM calls a function in the KM using an Ioctl, then the KM provides the requested parameters      "},
    {question="When does a packet, IF it is new, generate a log entry to be sent to the FWD process?", answer="Directly after it is inspected by the Chain Module, after it arrives at the gateway NIC"},
    {question="What is the full log chain when a packet is processed by a gateway?", answer="FW-FWD >>>> FW-CPD >>>> SMS-CPD >>>> SMS-FWD >>>> SMS-CPD >>>> SMS-CPM"},
    {question="What are packet process handlers which determine which modules will inspect a packet?", answer="Chain Modules"},
    {question="How many chains are in the Chain Modules?", answer="Two; inbound and outbound"},
    {question="Location Position FMDA", answer="Let’s Put Flaming Macaroni Down Attire"},
    {question="How do you examine how traffic moves through the Chain Modules from the CLI?", answer="fw monitor"},
    {question="Which fw monitor flag can you use to specify the relative position using location?", answer="-pi <location>"},
    {question="How do you limit the number of packets captured with fw monitor?", answer="Fw monitor -ci <count> -co <count>      (where ci is inbound and co is outbound)"},
    {question="How many symbolic links are kept for each connection in the connections table?", answer="3 additional links, outbound C2S, inbound S2C, and outbound S2C"},
    {question="How do you view the connections table from CLI?", answer="fwaccel conns"},
    {question="What kind of object does not have an IP assigned at creation, but has IP ranges assigned on the Gateway?", answer="Dynamic Objects"},
    {question="What kind of object allow external service providers to publish lists which are used to update IPs and Domains?", answer="Updatable Objects"},
    {question="How often is an Updatable Object updated by default?", answer="Every Hour"},
    {question="In which case (in R81) will policy installation NOT be accelerated?", answer="When NAT needs to be applied (when external networks are used)"},
    {question="How many policy installation tasks can be installed concurrently?", answer="Five"},
    {question="If you attempt to install more than the max concurrent policies at once, what happens?", answer="They are placed in a queue and installed in the order in which they were initiated."},
    {question="If you need to view changes done in a specific policy version, or revert to that version, where can you do this?", answer="Policy View > Access Tools > Installation History"},
    {question="What are the three stages of Policy Installation?", answer="I. Verification & Compilation (SMS)\nII. Transfer\nIII. Commit"},
    {question="When performing a Full Install Policy (as opposed to Fast), what additional Database Dump is required?", answer="From Postgres to old file formats for cpmitable (a dump from non cpmi, or Modern Dump, will always occur in both Full and Fast)"},
    {question="In the Fwd exec step of Verification & Compilation, where is the “fwm state” saved to before fwm is re-executed as a “fwd load” command to push the files?", answer="$FWDIR/tmp/"},
    {question="What language is a policy translated to, and by what compiler, during Code Generation and Compilation (they are the same)?", answer="INSPECT"},
    {question="After the fwm process compiles the relevant files, such as objects_5_0.C and AccessCTRRules_0.C into several compiled files (local.ft, local.set, etc.), what directory on the management server is the policy copied to?", answer="$FWDIR/state/<gateway name>"},
    {question="Which agent performs the transfer between the SMS & Gateway using encrypted connected SSL & SIC authentication?", answer="Check Point Transfer Agent"},
    {question="Which process on the Gateway executes the command to load the policy after being transferred to it?", answer="cpd"},
    {question="Which process on the Gateway updates all of the User Mode processes responsible for enforcement aspects?", answer="cpd"},
    {question="What is an automation tool to configure and view the Gaia OS parameters using CLI and web services?", answer="Gaia API"},
    {question="What is an automation tool to configure and/or view the security policy and objects in a SMS or MDS using CLI tools and web services?", answer="Management API"},
    {question="What is the difference between Automation and Orchestration?", answer="Automation is the automation of individual tasks that are normally performed with human intervention, where Orchestration is the organization of the flow of those tasks."},
    {question="What are the three key drivers for Automation & Orchestration?", answer="People, Processes, and Technology"},
    {question="What are the four ways to access the Management API?", answer="Web Services (POST calls to the SMS web server)\nSmartConsole - Gaia CLI (built-in CLI, login/logout not available because you have already done so before accessing)\nmgmt_cli (Linux or Windows (.exe))\nGaia Clish (on the SMS server's CLI)"},
    {question="When you make changes to the API server settings, what 2 steps must you take for the changes to take?", answer="Publish the changes, and then restart the API service"},
    {question="What commands would you use to restart the API service?", answer="'api restart', OR 'api stop & api start'"},
    {question="What command would you use to show the status of the API service on the SMS?", answer="api status"},
    {question="Except for the SmartConsole and command line API options, what must you obtain with a login command before running subsequent commands?", answer="SID"},
    {question="Which command flag allows you to pass a source file (such as a CSV) to mgmt_cli in order to process many items at once?", answer="--batch"},
    {question="After you have obtained your SID (session ID) from a login command and saved it to a file, what flag on subsequent commands allows you to use that SID to run the commands under your session?", answer="-s"},
    {question="At which URL can you access the API reference?", answer="https://sc1.checkpoint.com/documents/latest/APIs"},
    {question="Where is the AD (Acceleration Device) inserted when using SecureXL?", answer="Immediately after the NIC"},
    {question="When do the cores of a Gateway share the load for Acceleration (at what number of cores that the GW has)?", answer="1 or 2"},
    {question="When is a set number of cores set aside for Acceleration as SNDs (Secure Network Distributors)?", answer="4 or more"},
    {question="How many SNDs (Secure Network Distributors) can a GW have?", answer="As many as it has traffic interfaces (non mgmt).  Each Interface has an affinity for one SND."},
    {question="When using cores set aside as SNDs (Secure Network Distributors), what are the remaining cores used for?", answer="Traffic evaluation (non acceleration) after the SND has determined a NON-accelerated path"},
    {question="In which of the Three Packet Acceleration Paths are packets & connection NOT offloaded to the firewall cores for processing?", answer="Accelerated Path"},
    {question="In which of the Three Packet Acceleration Paths may the packet need deeper inspection?", answer="Medium Path"},
    {question="In which of the Three Packet Acceleration Paths are all packets & connections inspected by the FW Kernel, also known as the Slow Path?", answer="Firewall Path"},
    {question="Which of the Three Packet Acceleration Paths do New TCP connections (or comparable UDP) take?", answer="Firewall Path (Slow Path)"},
    {question="Which TWO of the Three Packet Acceleration Paths may previously processed packets that are approved by the firewall take?", answer="Accelerated or Medium Path"},
    {question="Which five attributes must match for source packets to be processed by the Accelerated Path?", answer="Source & Dest IP and Port (4 attributes total), and Protocol"},
    {question="Which legacy feature, when enabled, does not allow a packet to be accelerated?", answer="SDF (Sticky Decision Function)"},
    {question="Are connection to the GW itself eligible for acceleration?", answer="No"},
    {question="Are connections involving Security Servers (Authentication, Antivirus, URL Filtering, Anti-spam, DNS enforcement) eligible for acceleration?", answer="No"},
    {question="Are connections involving Handlers, IPS features, or Multicast eligible for acceleration?", answer="No"},
    {question="How can you address different source ports not being accelerated?", answer="Source Port Masking"},
    {question="Which of the three SecureXL connection templates, disabled by default, is generated by policy rules to drop traffic that matches?", answer="Drop Template"},
    {question="Which of the three SecureXL connection templates, enabled by default, is generated when a connection is established by matching a new connection to a particular set of tuple attributes?", answer="Accept Template"},
    {question="Which of the three SecureXL connection templates, disabled by default in R80.10 and lower (enabled by default in R80.20 and higher), is generated to achieve high session rate for NAT?", answer="NAT Template"},
    {question="Which CLI command would you use to view/set acceleration configuration and view the connections?", answer="fwaccel"},
    {question="Which feature enabled the CoreXL connections to be dynamically assigned and reassigned as needed?", answer="Dynamic Dispatcher"},
    {question="Which feature, disabled by default, allows Gas to change the number of Kernel and SND cores without rebooting, based on the CPU utilization of the kernel?", answer="Dynamic Split/Balancing"},
    {question="How does the dsd (Dynamic Split Daemon) process, in three stages, manage Dynamic Split/Balancing?", answer="Examines current CPU utilization, Decides what changes to make, Add/removes CoreXL instances to SND or Kernel"},
    {question="When implementing SNDs, how many cores does each system need to have?", answer="Doesn’t matter as long as they have the same number (and that number is 4 or greater)"},
    {question="What feature, enabled by default in R80.40/81.10) allows the FW to prioritize traffic based on packet type once it has reached full (100%) load?", answer="Firewall Priority Queues"},
    {question="What are the default 8 priority queues, from 0-7 (0 is highest priority), of the Firewall Priority Queues?", answer="Routing, Control, Cluster Sync, High Priority, Light Data Queue, Default Data Queue, Log Notification, Heavy Data Queue"},
    {question="In which of the 8 priority queues of the Firewall Priority Queues can connections NOT migrate to a different priority?", answer="Routing, Cluster Sync, Log Notifications"},
    {question="If you want to add up to 8 additional priorities to the Firewall Priority Queues, which file do you need to edit, followed by a reboot?", answer="$FWDIR/conf/prioq.conf"},
    {question="With which CLI command would you change the mode in which Firewall Priority Queues is running?", answer="fw ctl multik prioq <mode, 0 to 2 for 3 different modes>     (0 is the default)"},
    {question="When assigning cores to IPv6 traffic in CoreXL, how many can you assign?", answer="An equal or fewer number than IPv4 (cannot exceed IPv4 assignments)"},
    {question="Which CoreXL feature should be enabled when SND CPU load is high, CoreXL instance Cpu load is low, and no CPU cores are left to be assigned the SND by changing interface affinity?  This allows you to configure more than one traffic queue for each NIC.", answer="Multiple Traffic Queues"},
    {question="Which Check Point Acceleration option provides Load Balancing & HA to the gatways?", answer="ClusterXL"},
    {question="Which Check Point Acceleration option uses State Inspection technology and connection templates?", answer="SecureXL"},
    {question="Which Check Point Acceleration option uses SND (Secure Network Distributor) cores to decide which acceleration path the traffic will take?", answer="CoreXL"},
    {question="Which Three components do Check Point VPNs secure connections between?", answer="Checkpoint Domain GWs,  Non-Checkpoint Gateways, and Remote Users"},
    {question="What is an Interoperable Device in the context of Check Point VPNs?", answer="A Non-Checkpoint VPN Gateway"},
    {question="Which blade do Remote Users use when connecting to the VPN when using an Agent?", answer="IPSEC VPN Blade"},
    {question="Which blade do Remote Users use when connecting to the VPN when using a Browser?", answer="Mobile Access Blade"},
    {question="What refers to all the gateways and domains, and all the tunnels created by a single VPN configuration?", answer="VPN Community"},
    {question="What refers to the resources/hosts behind the Gateway available during a VPN connection?", answer="VPN Domain"},
    {question="What refers to the GW community member and the domain it protects in VPN context?", answer="VPN Site"},
    {question="Which type of VPN routes traffic based on the VPN Domain behind each gateway?", answer="Domain-Based VPN"},
    {question="Which type of VPN uses a Virtual Tunnel Interface (VTI) for each VPN Tunnel with a peer VPN Gateway?", answer="Route-Based VPN"},
    {question="What is the difference between a Star and Mesh VPN topology?", answer="In a Mesh topology, all gateways connect to all gateways, where in a Star topology, all Satellite gateways connect to a Central Gateway, and do not connect to each other."},
    {question="How do two Checkpoint gateways in the same Domain authenticate with each other for Site-to-Site VPNs?", answer="Using the SIC cert to verify peer identity"},
    {question="How do Remote External Gateways authenticate for Site-to-Site VPNs when both gateways are Checkpoint?", answer="With certificates issued by trusted CA"},
    {question="How do Remote External Gateways authenticate for Site-to-Site VPNs for non-Checkpoint gateways?", answer="With a Shared Secret for non-local SMS/non-CP gateways"},
    {question="Which component of the IPSec VPN protocol ensures data has not been tampered with (data integrity)?", answer="Authentication Header"},
    {question="Which component of the IPSec VPN protocol ensures confidentiality, integrity, origin authenticity & anti-replay?", answer="Encapsulating Security Payload"},
    {question="Which component of the IPSec VPN protocol defines the agreement negotiated between two peers, including the IKE and IPSec types?", answer="Security Association"},
    {question="In Phase 1 of IPSec authentication, what are the two modes available and what is the difference?", answer="Main Mode transmits 6 packets and includes peer authentication, Aggressive Mode transmits 3 packets and DOES NOT include authentication."},
    {question="When configuring VPN routing setting for Start topology VPNs, what is the default setting?", answer="To center only"},
    {question="Which IKE versions are supported for Remote Access?", answer="Version 1 only"},
    {question="Which IKE versions are supported on VPN Gateways?", answer="Versions 1 and 2"},
    {question="What relatively new Endpoint Client authentication method allows machine authentication before and after the user logs in to Windows?", answer="Machine Certificate"},
    {question="Can you use Remote Access VPN or Mobile Access VPN without a license?", answer="No, the IPSec VPN License is required for Remote Access and Mobile Access License is required for Mobile Access."},
    {question="Which Remote Access Solution encrypts traffic between the client and VPN gateway and allows remote access to corporate resources?", answer="Secure Connectivity"},
    {question="Which Remote Access Solution ensures devices connecting to the gateway meet security requirements, and provides limited or no connectivity if they do not?", answer="Security Verification"},
    {question="Which Remote Access Solution protects endpoint computers, even when there is no connectivity to the corporate network?  This uses an integrated desktop firewall and requires licenses based on the number of clients installed.", answer="Endpoint Security"},
    {question="Which Remote Access Solution includes several more blades to protect the endpoint, including Full Disk Encryption, Media Encryption, SandBlast Agent, and Anti-Malware?", answer="Total Endpoint Security"},
    {question="What is a thin SSL VPN on-demand client installed automatically through the web browser as a plug-in?", answer="SSL Network Extender (SNX)"},
    {question="What is the clientless SSL VPN solution used for Web/Mobile Access?", answer="SSL VPN Portal"},
    {question="Which full Layer-3 tunnel client is available for both PC and MAC and provides secure access from any application to the business?", answer="Endpoint Security VPN"},
    {question="Which full Layer-3 tunnel client is only available for PC (not MAC)?", answer="Check Point Mobile for Windows"},
    {question="Which BASIC layer-3 tunnel client is available for PC that does not include enterprise features (office mode)?", answer="SecuRemote"},
    {question="What clientless application for mobile devices creates a secure container on the device that isolates the VPN traffic and data?", answer="Capsule Workspace"},
    {question="What full L3 tunnel app gives users network access to all mobile applications?", answer="Capsule VPN/Connect"},
    {question="Which SSL Network Extender (SNX) mode does not require install privileges but only allows app access from within the Mobile Access Portal?", answer="Application Mode"},
    {question="Which SSL Network Extender (SNX) mode requires install privileges and allows app access from both the desktop and the Mobile Access Portal?", answer="Network Mode"},
    {question="What setting allows SSL Network Extender (SNX) to decide which mode to use based on the end-point capabilities?", answer="Automatic"},
    {question="Which mobile access option features offline data encryption, policy and remote wipe, and sharing control?", answer="Capsule Workspace"},
    {question="What VPN Client feature add a UDP header to the ESP packets so they can pass through a Hide NAT device?", answer="NAT-Traversal (also called UDP Encapsulation)"},
    {question="What VPN Client mode tunnels traffic through HTTPS to work with networks that only allow web traffic?", answer="Visitor Mode"},
    {question="What VPN Client mode directs all Remote Access Client traffic through a VPN Gateway?", answer="Hub Mode"},
    {question="What feature, available only to Remote Access Clients, allows clients to choose alternate gateways in case one fails?", answer="Multiple Entry Points (MEP)"},
    {question="What are the three MEP (Multiple Entry Point) methods?", answer="First to Respond, Primary/Backup, Random Selection"},
    {question="If you want to manually configure MEP (Multiple Entry Point), which file do you edit?", answer="$FWDIR/conf/trac_client_1.ttm"},
    {question="When using the Mobile Access portal, what needs to change in order to keep accessing the Gaia OS Portal over a web browser?", answer="The port needs to be changed off of 443 (usually 4434)"},
    {question="How would you customize the Mobile Access blade upon enabling it?", answer="Through the Built-In Configuration Wizard"},
    {question="How would you specify a specific web application that Mobile Access users can access?", answer="The Custom Web Application option in the Configuration Wizard"},
    {question="How would you specify email access for Mobile Access users?", answer="Mail/Calendar/Contacts option in the Configuration Wizard"},
    {question="Where would you configure additional options, such as File shares, Citrix services, and Native Apps?", answer="SmartDashboard/Smart Console"},
    {question="What auth method can only be used as the first method for Mobile Access?", answer="Certificate"},
    {question="What methods other than Certificate and Dynamic ID OTP can be used by Mobile Access?", answer="RADIUS, SecurID, Username & Password (LDAP)"},
    {question="What auth method CANNOT be used as the first method for Mobile Access?", answer="Dynamic ID OTP"},
    {question="Where would you configure Mobile Access Policies pre-R80?", answer="Smart Dashboard"},
    {question="What components comprise a Mobile Access Policy rule?", answer="Users (or groups), Applications (to be accessed), Gateways to install on"},
    {question="For an environment to use Unified Access Policy (SmartConsole), what setting must all the participating gateways use?", answer="Gateway > Mobile Access > Unified Access Policy (as opposed to Legacy Policy)"},
    {question="How would you define an application to be used in a Mobile Access or Unified Access Policy?", answer="New > More > Custom Application > Site > Mobile Application"},
    {question="What is the maximum number of gateways supported by Cluster XL for one cluster?", answer="Five"},
    {question="On what type of server is Full High Availability not available (concerning ClusterXL)?", answer="Open Servers (non-checkpoint hardware)"},
    {question="In which ClusterXL Mode does one GW handle 100% of the traffic?", answer="High Availability"},
    {question="In which ClusterXL Mode do all members actively share the traffic?", answer="Load Sharing"},
    {question="How does ClusterXL Load Sharing handle Multicast and Unicast?", answer="Multicast - all members receive, one member processes, other members drop.  Unicast - One member (Pivot) receives all traffic and allocates it to specific gateways."},
    {question="In which ClsuterXL Mode are gateways separated on different networks or geographically, handling different traffic until a failover occurs?", answer="Active/Active"},
    {question="Where would you go to enable/disable ClusterXL?", answer="cpconfig"},
    {question="What term means a system is configured to participate in a cluster and is 'actively' part of the cluster (not necessarily Active or passing traffic)?", answer="Active Up"},
    {question="What protocol allows gateways to report their own states and learn about the states of other members in the cluster?", answer="Cluster Control Protocol (CCP)"},
    {question="What Advanced Setting of ClusterXL will sync state tables to ensure transparent failover?", answer="State Synchronization"},
    {question="What will the Virtual MAC option of ClusterXL do?", answer="Creates a VMAC for the interfaces that all cluster members respond to."},
    {question="How would you configure ClusterXL to switch back to the higher priority member upon recovery of that member?", answer="Change the 'Upon cluster member Recover' option"},
    {question="How do you ensure that outbound traffic returns through the same gateway in ClusterXL Load Sharing?", answer="Sticky Decision Function (SDF)"},
    {question="Which state synchronization type occurs during initial transfer of state information, or when a GW is brought up after failover, and what port does it operate on?", answer="Full Sync, TCP port 256"},
    {question="Which state synchronization type occurs when changes are made to the kernel table, and what port does it operate on?", answer="Delta Sync, UDP port 8116"},
    {question="What are the three requirements for cluster members to be synchronized?", answer="Same platform, Same software version (prior to 80.40), Same CPU Count"},
    {question="What type of connection will in all cases be lost if a cluster member fails?", answer="User Authenticated Connection"},
    {question="What types of connections can be retained if a cluster member fails?", answer="Client Authenticated or Session Authenticated"},
    {question="What handles asynchronous connections in R80.20 and later?", answer="Cluster Correction Layer (CCL)"},
    {question="When using Cluster Correction Layer (CCL), what two types of corrections can occur when a connection is sent back through a different gateway than it arrived?", answer="Dispatcher correction, where the dispatcher, or the gateway that receives the packet, corrects, and Late Correction, where it cannot be corrected until after it has reached the Kernel."},
    {question="What is the preferred method for initiating a manual ClusterXL failover?", answer="clsuterXL_admin down -p    (p makes it persistent)"},
    {question="Which blade determines if a network is compliant with best practices and identifies policy and config weaknesses?", answer="Compliance Software Blade"},
    {question="What is used to optimally configure Software Blades & settings, used by Compliance Software Blade to compare changes against best practices?", answer="Best Practices Library"},
    {question="What are the two types of Best Practice Tests, and what do they test?", answer="Global - tests config settings for the org.  Object-based - tests particular objects, such as gateways and profiles"},
    {question="Which compliance standard emphases more security during the development, implementation, and operation of more secure information systems, defining following 17 security areas covered under the CIA triad?", answer="Federal Information Processing Standard Publication 200, or FIPS 200"},
    {question="Which compliance standard requires government agencies, insurers and health care providers to protect all data that they collect maintain or use?", answer="HIPPA Security"},
    {question="Which compliance standard defines standards for the implementation of Information Security Management Systems (ISMS)?", answer="ISO 27001"},
    {question="Which compliance standard supplements standards for the implementation of Information Security Management Systems (ISMS)?", answer="ISO 27002"},
    {question="Which compliance standards deal with Payment Card data?", answer="PCI DSS (2.0 and 3.0)"},
    {question="Which compliance standard is a good-practice framework and supporting tool set created by ISACA, allowing managers to bridge the gap between control requirements, technical issues and business risks?", answer="COBIT 4.1"},
    {question="When compliance degradation is detected, what is generated that will detail corrective action and will persist until corrective actions have been taken and another scan has been performed?", answer="Action Items"},
    {question="What is a unified security event management and analysis solution that delivers graphical threat management information?", answer="Smart Event"},
    {question="What is the difference between a log and an event?", answer="A log is a record of an action performed by a Blade, an event is a record of an incident that is based on one or more logs, defined by a customizable set of rules."},
    {question="Where is the set of rules governing what is determined to be an event?", answer="The Event Policy"},
    {question="What identified events when there is a suspicious pattern of two or more logs, and what port does this use?", answer="Correlation Unit, TCP 18184 (Log Export API (LEA)) protocol"},
    {question="What is the Smart Event term for a log that is not individually an Event, but may be the start of one, found by the Correlation Unit?", answer="Event Candidate"},
    {question="Where does the Correlation Unit forward events after identifying a threat pattern?", answer="SmartEvent Server"},
    {question="What does SmartEvent ALWAYS do to an event received?", answer="Assigns a severity level to the event"},
    {question="What does SmartEvent OPTIONALLY do to an event received?", answer="Initiate a pre-determined action on the traffic"},
    {question="What are the 3 options for SmartEvent Clients?", answer="SmartEvent GUI, SmartConsole, SmartView Web UI (https://<sms_ip_or_hostname>/smartview/)"},
    {question="How do Administrators set the limits for logs to become an event?", answer="Event Thresholds"},
    {question="What directs SmartEvent to ignore logs that are not expected to contribute to an event, causing matching logs to be discarded by the system.", answer="Global Exclusions"}
}